# Br br
name: My-Github-Actions

on: 
  push:
    branches:
      - main
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print nice message from testing
        run: echo "Hello World! from testing"

      - name: execute few commands
        run: |
          echo "Message 1"
          echo "Message 2"

      - name: Check files
        run: ls -la

      - name: Clone my repo
        uses: actions/checkout@v1

      - name: Check files
        run: ls -la
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print nice message from deploy
        run: echo "Hello World! from deploy"

      - name: Check files
        run: ls -la
