# Br br
name: My-Github-Actions
env:
  APP_NAME: "My App"
  DEPLOY_PACKAGE_NAME: "app-ver-${{ github.sha }}"

on: 
  push:
    branches:
      - main
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print nice message from testing
        run: echo "Hello World! from testing"

      - name: execute few commands
        run: |
          echo "Message 1"
          echo "Message 2"
          echo "Print global var ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Check files
        run: ls -la

      - name: Clone my repo
        uses: actions/checkout@v1

      - name: Check files
        run: ls -la
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "Job variable 1"
      VAR2: "Job variable 2"
    
    steps:
      - name: Print nice message from deploy
        run: echo "Hello World! from deploy"

      - name: Check files
        run: ls -la

      - name: Print some info
        run: echo "App var is ${{ env.APP_NAME }}"

      - name: Print some more info
        run: |
          echo "Job var1 is ${{ env.VAR1 }}"
          echo "Job var2 is ${{ env.VAR2 }}"

      - name: Print local var
        run: echo "Local var is $LOCAL_VAR"
        env:
          LOCAL_VAR: "I'm local var"

      - name: Check if aws exists
        run: aws --version

      - name: Check if ZIP exists
        run: zip --version
